baseURL = 'https://jlevesy.github.io/talks'
languageCode = 'en-us'
title = 'Introduction to Kubernetes'
theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
